### ISSUE TITLE
Hodor hodor

### ISSUE THREAD

**Issue by jtimberman** [jkeiser/hodorhodor#1]
Hodor hodor.

Hordor hordor, hordor hordor hordor hordor. Hordor hordor hordor hordor?

``` ruby
hordor hordor
hordor = hordor?
hordor.has_hordor? #=> hordor
```

**Comment by jkeiser** [comment]
:+1: hodor `has_hodor?` hodor hodor.  Hodor hodor; hodor hodor hodor hodor hodor https://github.com/jtimberman/hodorhodor/compare/ hodor hodor.

**Comment by mattstratton** [comment]
Hodor??? Hodor hodor hodor, hodor Windows support????

**Comment by jkeiser** [comment]
@mattstratton Hodor hodor :8ball:.  Hodor hodor https://github.com/jkeiser/hodorhodor/wiki hodor hodorhodor.

**Comment by jkeiser** [comment]
Hodor hodor Windows hodor.  Hodor HODOR HODOR Windows hodor.  Hodor.
